name: cloudnex_ops_dashboard
description: CloudNex Enterprise DevOps and Serverless RAG Monitor Client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
   

  cupertino_icons: ^1.0.6

  # ✅ Enterprise Network & Security
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # ✅ ASSETS (ADD YOUR LOGO HERE)
  assets:
    - assets/images/logo.jpg