name: cloudnex_ops_dashboard
description: CloudNex Enterprise DevOps and Serverless RAG Monitor Client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # ✅ Enterprise Network & Security
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # ✅ Icon Automation
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  # ✅ ASSETS
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false # Disabled to optimize build speed
  image_path: "assets/images/logo.png"
  min_sdk_android: 21