FROM mcr.microsoft.com/devcontainers/flutter:latest

# Install Android SDK Command Line Tools
RUN mkdir -p /home/codespace/Android/Sdk && \
    chown -R codespace:codespace /home/codespace/Android/Sdk